antora:
  extensions:
  - '@antora/collector-extension'
  - id: '@antora/atlas-extension'
    require: '@antora/atlas-extension'
    enabled: false
  - '@opendevise/antora-release-line-extension'
  - require: '@springio/antora-extensions/tabs-migration-extension'
    unwrap_example_block: always
site:
  title: Spring Boot
content:
  sources:
    - url: ./../..
      branches: HEAD
      start_paths: 
      - spring-boot-project/spring-boot-docs/build/antora
ext:
  zip_content_collector:
    include: 
    - url: build/generated/spring-boot-docs-antora.zip
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
    include-java: 'reference:example$src/main/java/org/springframework/boot/docs'
    include-kotlin: 'reference:example$src/main/kotlin/org/springframework/boot/docs'
    docs-resources: 'example$src/main/resources'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
    - '@springio/asciidoctor-extensions/configuration-properties-extension'
    - '@springio/asciidoctor-extensions/section-ids-extension'
  sourcemap: true
urls:
  latest_version_segment: ''
runtime:
  log:
    failure_level: warn
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
